// src/type/container/type.ts
export const TYPES = {
    AdmissionController: Symbol.for("AdmissionController"),
    AdmissionRepository: Symbol.for("AdmissionRepository"),
    AdmissionService: Symbol.for("AdmissionService"),
    AuthService: Symbol.for("AuthService"),
    AwardRepository: Symbol.for("AwardRepository"),
    AwardService: Symbol.for("AwardService"),
    CertificationRepository: Symbol.for("CertificationRepository"),
    CertificationService: Symbol.for("CertificationService"),
    ClientConfig: Symbol.for("ClientConfig"),
    DataSource: Symbol.for("DataSource"),
    EventListenerManager: Symbol.for("EventListenerManager"),
    FileRepository: Symbol.for("FileRepository"),
    FileService: Symbol.for("FileService"),
    IJwtTokenRepository: Symbol.for("IJwtTokenRepository"),
    InversifyContainer: Symbol.for("InversifyContainer"),
    IUserRepository: Symbol.for("IUserRepository"),
    JwtEntityService: Symbol.for("JwtEntityService"),
    JWTService: Symbol.for("JWTService"),
    KeyStore: Symbol.for("KeyStore"),
    Logger: Symbol.for("Logger"),
    MajorGroupRepository: Symbol.for("MajorGroupRepository"),
    MajorRepository: Symbol.for("MajorRepository"),
    MajorService: Symbol.for("MajorService"),
    MistralService: Symbol.for("MistralService"),
    OcrEventListenerService: Symbol.for("OcrEventListenerService"),
    OcrResultRepository: Symbol.for("OcrResultRepository"),
    OcrResultService: Symbol.for("OcrResultService"),
    PassportConfig: Symbol.for("PassportConfig"),
    PredictHttpClient: Symbol.for("PredictHttpClient"),
    PredictionModelEventListenerService: Symbol.for(
        "PredictionModelEventListenerService",
    ),
    PredictionModelService: Symbol.for("PredictionModelService"),
    PredictionModelServiceConfig: Symbol.for("PredictionModelServiceConfig"),
    PredictionResultEntityRepository: Symbol.for(
        "PredictionResultEntityRepository",
    ),
    PredictionResultRepository: Symbol.for("PredictionResultRepository"),
    PredictionResultService: Symbol.for("PredictionResultService"),
    PredictionServiceClient: Symbol.for("PredictionServiceClient"),
    RedisPublisher: Symbol.for("RedisPublisher"),
    RedisSubscriber: Symbol.for("RedisSubscriber"),
    StudentRepository: Symbol.for("StudentRepository"),
    StudentService: Symbol.for("StudentService"),
    TokenCleanupJob: Symbol.for("TokenCleanupJob"),
    UserRepository: Symbol.for("UserRepository"),
    UserService: Symbol.for("UserService"),
};
