// src/type/container/type.ts
export const TYPES = {
    AuthService: Symbol.for("AuthService"),
    AwardRepository: Symbol.for("AwardRepository"),
    AwardService: Symbol.for("AwardService"),
    CertificationRepository: Symbol.for("CertificationRepository"),
    CertificationService: Symbol.for("CertificationService"),
    FileRepository: Symbol.for("FileRepository"),
    FileService: Symbol.for("FileService"),
    IJwtTokenRepository: Symbol.for("IJwtTokenRepository"),
    IUserRepository: Symbol.for("IUserRepository"),
    JwtEntityService: Symbol.for("JwtEntityService"),
    JWTService: Symbol.for("JWTService"),
    KeyStore: Symbol.for("KeyStore"),
    Logger: Symbol.for("Logger"),
    MajorGroupRepository: Symbol.for("MajorGroupRepository"),
    MajorRepository: Symbol.for("MajorRepository"),
    MajorService: Symbol.for("MajorService"),
    PassportConfig: Symbol.for("PassportConfig"),
    StudentRepository: Symbol.for("StudentRepository"),
    StudentService: Symbol.for("StudentService"),
    TokenCleanupJob: Symbol.for("TokenCleanupJob"),
    UserRepository: Symbol.for("UserRepository"),
    UserService: Symbol.for("UserService"),
} as const;
