import { PredictModelServiceConfig } from "@/service/predict.model.service.js";
import { ClientConfig } from "@/type/class/prediction.service.client.js";
import { config } from "@/util/validate.env.js";

export const predictModelServiceConfig: PredictModelServiceConfig = {
    SERVER_BATCH_CONCURRENCY: config.SERVER_BATCH_CONCURRENCY,
    SERVICE_BATCH_CONCURRENCY: config.SERVICE_BATCH_CONCURRENCY,
    SERVICE_CHUNK_SIZE_INPUT_ARRAY: config.SERVICE_CHUNK_SIZE_INPUT_ARRAY,
    SERVICE_INPUTS_PER_WORKER: config.SERVICE_INPUTS_PER_WORKER,
    SERVICE_MAX_RETRIES: config.SERVICE_MAX_RETRIES,
    SERVICE_MIN_BATCH_CONCURRENCY: config.SERVICE_MIN_BATCH_CONCURRENCY,
    SERVICE_NETWORK_LATENCY_MS: config.SERVICE_NETWORK_LATENCY_MS,
    SERVICE_PREDICTION_CONCURRENCY: config.SERVICE_PREDICTION_CONCURRENCY,
    SERVICE_REQUEST_DELAY_MS: config.SERVICE_REQUEST_DELAY_MS,
    SERVICE_RETRY_BASE_DELAY_MS: config.SERVICE_RETRY_BASE_DELAY_MS,
    SERVICE_RETRY_ITERATION_DELAY_MS: config.SERVICE_RETRY_ITERATION_DELAY_MS,
} as const;

export const predictModelServerConfig: ClientConfig = {
    SERVICE_SERVER_HOSTNAME: config.SERVICE_SERVER_HOSTNAME,
    SERVICE_SERVER_PATH: config.SERVICE_SERVER_PATH,
    SERVICE_SERVER_PORT: config.SERVICE_SERVER_PORT,
    SERVICE_TIMEOUT_IN_MS: config.SERVICE_TIMEOUT_IN_MS,
} as const;
