// src/config/swagger.ts
import { Express, Request, Response } from "express";
import swaggerUi from "swagger-ui-express";

// Import the swagger.json file generated by TSOA
import * as swaggerJson from "@/generated/swagger.json";
import log from "@/util/logger.js";

function swaggerDocs(app: Express, port: number): void {
  // Swagger page
  app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerJson));

  // Docs in JSON format
  app.get("/docs.json", (req: Request, res: Response) => {
    res.setHeader("Content-Type", "application/json");
    res.send(swaggerJson);
  });

  log.info(`Docs available at http://localhost:${port.toString()}/docs`);
}

export default swaggerDocs;
