// src/config/swagger.ts

import { Express, Request, Response } from "express";
import swaggerUi from "swagger-ui-express";

// Import the swagger.json file generated by TSOA
import swaggerJson from "@/generated/swagger.json";
import log from "@/util/logger.js";

// The imported JSON is a mutable object, so we can modify it.
const swaggerSpec = swaggerJson;

function swaggerDocs(app: Express, serverUrl: string): void {
  // <-- UPDATED PARAMETER NAME
  // Dynamically set the server URL in the Swagger spec
  swaggerSpec.servers = [
    {
      url: serverUrl,
    },
  ];

  // Swagger page
  app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec)); // <-- Use the modified spec

  // Docs in JSON format
  app.get("/docs.json", (req: Request, res: Response) => {
    res.setHeader("Content-Type", "application/json");
    res.send(swaggerSpec); // <-- Serve the modified spec
  });

  // The log message no longer needs to construct the URL manually
  log.info(`Docs available at ${serverUrl.replace("/api", "/docs")}`);
}

export default swaggerDocs;
